"""add answer correctness metrics

Revision ID: 33ee30915355
Revises: 9014cc288cff
Create Date: 2026-09-02 13:57:40.273340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ee30915355'
down_revision: Union[str, Sequence[str], None] = '9014cc288cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_results', sa.Column('answer_similarity', sa.Float(), nullable=False))
    op.add_column('evaluation_results', sa.Column('answer_correct', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_results', 'answer_correct')
    op.drop_column('evaluation_results', 'answer_similarity')
    # ### end Alembic commands ###
