"""add faithfulness metrics

Revision ID: d306de142f3d
Revises: 33ee30915355
Create Date: 2026-09-02 14:03:25.677967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd306de142f3d'
down_revision: Union[str, Sequence[str], None] = '33ee30915355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_results', sa.Column('faithfulness_score', sa.Float(), nullable=False))
    op.add_column('evaluation_results', sa.Column('faithful', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_results', 'faithful')
    op.drop_column('evaluation_results', 'faithfulness_score')
    # ### end Alembic commands ###
